package com.zy.study.bootstudy.mapper1;

import com.zy.study.bootstudy.entity1.TbTaxpayer;
import com.zy.study.bootstudy.entity1.TbTaxpayerExample;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface TbTaxpayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    int countByExample(TbTaxpayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    int deleteByExample(TbTaxpayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal taxpayerUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    int insert(TbTaxpayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    int insertSelective(TbTaxpayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    List<TbTaxpayer> selectByExample(TbTaxpayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    TbTaxpayer selectByPrimaryKey(BigDecimal taxpayerUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbTaxpayer record, @Param("example") TbTaxpayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    int updateByExample(@Param("record") TbTaxpayer record, @Param("example") TbTaxpayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    int updateByPrimaryKeySelective(TbTaxpayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    int updateByPrimaryKey(TbTaxpayer record);
}