package com.zy.study.bootstudy.entity1;

import com.zy.study.bootstudy.utils.poi.ModelProp;
import com.zy.study.bootstudy.utils.poi.ModelTitle;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

@ModelTitle(name = "Invoice")
@Table(name = "TB_INVOICE")
public class TbInvoice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVOICE_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    @ModelProp(colIndex = 0,name = "Invoice Uid")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY,
            generator = "select SEQ_TB_INVOICE.nextval from dual")
    private Integer invoiceUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVOICE_NO
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    @ModelProp(colIndex = 1,name = "Invoice No")
    private String invoiceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVOICE_SHORT_CODE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    @ModelProp(colIndex = 2,name = "Invoice Short Code")
    private String invoiceShortCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TAXPAYER_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private Integer taxpayerUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.DEVICE_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private Integer deviceUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVOICE_MADE_BY
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String invoiceMadeBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVOICE_FROM
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String invoiceFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVOICE_TYPE_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private Integer invoiceTypeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVOICE_TYPE_CODE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String invoiceTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVOICE_TYPE_NAME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String invoiceTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.DRAWER_NAME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String drawerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.CLIENT_INVOICE_DATETIME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private Date clientInvoiceDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.PURCHASER_TIN
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String purchaserTin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.PURCHASER_NAME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String purchaserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.PURCHASER_ADDRESS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String purchaserAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.PURCHASER_PHONE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String purchaserPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.PURCHASER_ID_TYPE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String purchaserIdType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.PURCHASER_ID_NUMBER
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String purchaserIdNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.SELLER_TIN
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    @ModelProp(colIndex = 3,name = "Seller Tin")
    private String sellerTin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.SELLER_NAME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    @ModelProp(colIndex = 4,name = "Seller Name")
    private String sellerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.SELLER_ADDRESS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    @ModelProp(colIndex = 5,name = "Seller Address")
    private String sellerAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.SELLER_PHONE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    @ModelProp(colIndex = 6,name = "Seller Phone")
    private String sellerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.SELLER_BRANCH_ADDR
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String sellerBranchAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.IS_LOCAL_CURRENCY
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String isLocalCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.CURRENCY_CODE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String currencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.EXCHANGE_RATE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private BigDecimal exchangeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TOTAL_FINAL
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private BigDecimal totalFinal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TOTAL_VAT
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private BigDecimal totalVat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TOTAL_STAMP
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private BigDecimal totalStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TOTAL_BPT
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private BigDecimal totalBpt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TOTAL_TAX1
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private BigDecimal totalTax1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TOTAL_TAX2
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private BigDecimal totalTax2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TOTAL_TAX3
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private BigDecimal totalTax3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TOTAL_TAX4
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private BigDecimal totalTax4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TOTAL_TAX5
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private BigDecimal totalTax5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TOTAL_TAXABLE_AMOUNT_ORG
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private BigDecimal totalTaxableAmountOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TOTAL_TAXABLE_AMOUNT
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    @ModelProp(colIndex = 7,name = "Taxable Amount")
    private BigDecimal totalTaxableAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TOTAL_TAX_DUE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    @ModelProp(colIndex = 8,name = "Tax Due")
    private BigDecimal totalTaxDue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.TOTAL_ALL
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    @ModelProp(colIndex = 9,name = "Tax All")
    private BigDecimal totalAll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.REMARK
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.STATUS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.NEGATIVE_FLAG
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String negativeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.DEDUCTION_STATUS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String deductionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.APPLIED_NEGATIVE_TOTAL_AMOUNT
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private BigDecimal appliedNegativeTotalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.ORG_INVOICE_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private Integer orgInvoiceUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.NEGATIVE_APPRIVAL_USER_ID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String negativeApprivalUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.NEGATIVE_APPROVAL_REMARK
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String negativeApprovalRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.NEGATIVE_APPROVAL_DATETIME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private Date negativeApprovalDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVALID_FLAG
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String invalidFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVALID_DATETIME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private Date invalidDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVALID_USER_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String invalidUserUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVALID_REMARK
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String invalidRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.IS_RAFFLED
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String isRaffled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.IS_LUCKY
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String isLucky;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.CASH_DATE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private Date cashDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.IS_UPLOADED
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String isUploaded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.PRINT_FLAG
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String printFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.IS_DEDUCTABLE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String isDeductable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.CRT_DATETIME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    @ModelProp(colIndex = 10,name = "Date")
    private Date crtDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.IS_EINVOICE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String isEinvoice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVOICE_PROCESS_STATUS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String invoiceProcessStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.INVOICE_REQUEST_TYPE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String invoiceRequestType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_INVOICE.SIGN
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    private String sign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVOICE_UID
     *
     * @return the value of TB_INVOICE.INVOICE_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public Integer getInvoiceUid() {
        return invoiceUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVOICE_UID
     *
     * @param invoiceUid the value for TB_INVOICE.INVOICE_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvoiceUid(Integer invoiceUid) {
        this.invoiceUid = invoiceUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVOICE_NO
     *
     * @return the value of TB_INVOICE.INVOICE_NO
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVOICE_NO
     *
     * @param invoiceNo the value for TB_INVOICE.INVOICE_NO
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVOICE_SHORT_CODE
     *
     * @return the value of TB_INVOICE.INVOICE_SHORT_CODE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getInvoiceShortCode() {
        return invoiceShortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVOICE_SHORT_CODE
     *
     * @param invoiceShortCode the value for TB_INVOICE.INVOICE_SHORT_CODE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvoiceShortCode(String invoiceShortCode) {
        this.invoiceShortCode = invoiceShortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TAXPAYER_UID
     *
     * @return the value of TB_INVOICE.TAXPAYER_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public Integer getTaxpayerUid() {
        return taxpayerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TAXPAYER_UID
     *
     * @param taxpayerUid the value for TB_INVOICE.TAXPAYER_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTaxpayerUid(Integer taxpayerUid) {
        this.taxpayerUid = taxpayerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.DEVICE_UID
     *
     * @return the value of TB_INVOICE.DEVICE_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public Integer getDeviceUid() {
        return deviceUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.DEVICE_UID
     *
     * @param deviceUid the value for TB_INVOICE.DEVICE_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setDeviceUid(Integer deviceUid) {
        this.deviceUid = deviceUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVOICE_MADE_BY
     *
     * @return the value of TB_INVOICE.INVOICE_MADE_BY
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getInvoiceMadeBy() {
        return invoiceMadeBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVOICE_MADE_BY
     *
     * @param invoiceMadeBy the value for TB_INVOICE.INVOICE_MADE_BY
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvoiceMadeBy(String invoiceMadeBy) {
        this.invoiceMadeBy = invoiceMadeBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVOICE_FROM
     *
     * @return the value of TB_INVOICE.INVOICE_FROM
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getInvoiceFrom() {
        return invoiceFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVOICE_FROM
     *
     * @param invoiceFrom the value for TB_INVOICE.INVOICE_FROM
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvoiceFrom(String invoiceFrom) {
        this.invoiceFrom = invoiceFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVOICE_TYPE_UID
     *
     * @return the value of TB_INVOICE.INVOICE_TYPE_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public Integer getInvoiceTypeUid() {
        return invoiceTypeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVOICE_TYPE_UID
     *
     * @param invoiceTypeUid the value for TB_INVOICE.INVOICE_TYPE_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvoiceTypeUid(Integer invoiceTypeUid) {
        this.invoiceTypeUid = invoiceTypeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVOICE_TYPE_CODE
     *
     * @return the value of TB_INVOICE.INVOICE_TYPE_CODE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getInvoiceTypeCode() {
        return invoiceTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVOICE_TYPE_CODE
     *
     * @param invoiceTypeCode the value for TB_INVOICE.INVOICE_TYPE_CODE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvoiceTypeCode(String invoiceTypeCode) {
        this.invoiceTypeCode = invoiceTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVOICE_TYPE_NAME
     *
     * @return the value of TB_INVOICE.INVOICE_TYPE_NAME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getInvoiceTypeName() {
        return invoiceTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVOICE_TYPE_NAME
     *
     * @param invoiceTypeName the value for TB_INVOICE.INVOICE_TYPE_NAME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvoiceTypeName(String invoiceTypeName) {
        this.invoiceTypeName = invoiceTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.DRAWER_NAME
     *
     * @return the value of TB_INVOICE.DRAWER_NAME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getDrawerName() {
        return drawerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.DRAWER_NAME
     *
     * @param drawerName the value for TB_INVOICE.DRAWER_NAME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setDrawerName(String drawerName) {
        this.drawerName = drawerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.CLIENT_INVOICE_DATETIME
     *
     * @return the value of TB_INVOICE.CLIENT_INVOICE_DATETIME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public Date getClientInvoiceDatetime() {
        return clientInvoiceDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.CLIENT_INVOICE_DATETIME
     *
     * @param clientInvoiceDatetime the value for TB_INVOICE.CLIENT_INVOICE_DATETIME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setClientInvoiceDatetime(Date clientInvoiceDatetime) {
        this.clientInvoiceDatetime = clientInvoiceDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.PURCHASER_TIN
     *
     * @return the value of TB_INVOICE.PURCHASER_TIN
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getPurchaserTin() {
        return purchaserTin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.PURCHASER_TIN
     *
     * @param purchaserTin the value for TB_INVOICE.PURCHASER_TIN
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setPurchaserTin(String purchaserTin) {
        this.purchaserTin = purchaserTin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.PURCHASER_NAME
     *
     * @return the value of TB_INVOICE.PURCHASER_NAME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getPurchaserName() {
        return purchaserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.PURCHASER_NAME
     *
     * @param purchaserName the value for TB_INVOICE.PURCHASER_NAME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setPurchaserName(String purchaserName) {
        this.purchaserName = purchaserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.PURCHASER_ADDRESS
     *
     * @return the value of TB_INVOICE.PURCHASER_ADDRESS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getPurchaserAddress() {
        return purchaserAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.PURCHASER_ADDRESS
     *
     * @param purchaserAddress the value for TB_INVOICE.PURCHASER_ADDRESS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setPurchaserAddress(String purchaserAddress) {
        this.purchaserAddress = purchaserAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.PURCHASER_PHONE
     *
     * @return the value of TB_INVOICE.PURCHASER_PHONE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getPurchaserPhone() {
        return purchaserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.PURCHASER_PHONE
     *
     * @param purchaserPhone the value for TB_INVOICE.PURCHASER_PHONE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setPurchaserPhone(String purchaserPhone) {
        this.purchaserPhone = purchaserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.PURCHASER_ID_TYPE
     *
     * @return the value of TB_INVOICE.PURCHASER_ID_TYPE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getPurchaserIdType() {
        return purchaserIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.PURCHASER_ID_TYPE
     *
     * @param purchaserIdType the value for TB_INVOICE.PURCHASER_ID_TYPE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setPurchaserIdType(String purchaserIdType) {
        this.purchaserIdType = purchaserIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.PURCHASER_ID_NUMBER
     *
     * @return the value of TB_INVOICE.PURCHASER_ID_NUMBER
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getPurchaserIdNumber() {
        return purchaserIdNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.PURCHASER_ID_NUMBER
     *
     * @param purchaserIdNumber the value for TB_INVOICE.PURCHASER_ID_NUMBER
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setPurchaserIdNumber(String purchaserIdNumber) {
        this.purchaserIdNumber = purchaserIdNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.SELLER_TIN
     *
     * @return the value of TB_INVOICE.SELLER_TIN
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getSellerTin() {
        return sellerTin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.SELLER_TIN
     *
     * @param sellerTin the value for TB_INVOICE.SELLER_TIN
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setSellerTin(String sellerTin) {
        this.sellerTin = sellerTin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.SELLER_NAME
     *
     * @return the value of TB_INVOICE.SELLER_NAME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.SELLER_NAME
     *
     * @param sellerName the value for TB_INVOICE.SELLER_NAME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.SELLER_ADDRESS
     *
     * @return the value of TB_INVOICE.SELLER_ADDRESS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getSellerAddress() {
        return sellerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.SELLER_ADDRESS
     *
     * @param sellerAddress the value for TB_INVOICE.SELLER_ADDRESS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setSellerAddress(String sellerAddress) {
        this.sellerAddress = sellerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.SELLER_PHONE
     *
     * @return the value of TB_INVOICE.SELLER_PHONE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getSellerPhone() {
        return sellerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.SELLER_PHONE
     *
     * @param sellerPhone the value for TB_INVOICE.SELLER_PHONE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setSellerPhone(String sellerPhone) {
        this.sellerPhone = sellerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.SELLER_BRANCH_ADDR
     *
     * @return the value of TB_INVOICE.SELLER_BRANCH_ADDR
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getSellerBranchAddr() {
        return sellerBranchAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.SELLER_BRANCH_ADDR
     *
     * @param sellerBranchAddr the value for TB_INVOICE.SELLER_BRANCH_ADDR
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setSellerBranchAddr(String sellerBranchAddr) {
        this.sellerBranchAddr = sellerBranchAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.IS_LOCAL_CURRENCY
     *
     * @return the value of TB_INVOICE.IS_LOCAL_CURRENCY
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getIsLocalCurrency() {
        return isLocalCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.IS_LOCAL_CURRENCY
     *
     * @param isLocalCurrency the value for TB_INVOICE.IS_LOCAL_CURRENCY
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setIsLocalCurrency(String isLocalCurrency) {
        this.isLocalCurrency = isLocalCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.CURRENCY_CODE
     *
     * @return the value of TB_INVOICE.CURRENCY_CODE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.CURRENCY_CODE
     *
     * @param currencyCode the value for TB_INVOICE.CURRENCY_CODE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.EXCHANGE_RATE
     *
     * @return the value of TB_INVOICE.EXCHANGE_RATE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getExchangeRate() {
        return exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.EXCHANGE_RATE
     *
     * @param exchangeRate the value for TB_INVOICE.EXCHANGE_RATE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setExchangeRate(BigDecimal exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TOTAL_FINAL
     *
     * @return the value of TB_INVOICE.TOTAL_FINAL
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getTotalFinal() {
        return totalFinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TOTAL_FINAL
     *
     * @param totalFinal the value for TB_INVOICE.TOTAL_FINAL
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTotalFinal(BigDecimal totalFinal) {
        this.totalFinal = totalFinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TOTAL_VAT
     *
     * @return the value of TB_INVOICE.TOTAL_VAT
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getTotalVat() {
        return totalVat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TOTAL_VAT
     *
     * @param totalVat the value for TB_INVOICE.TOTAL_VAT
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTotalVat(BigDecimal totalVat) {
        this.totalVat = totalVat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TOTAL_STAMP
     *
     * @return the value of TB_INVOICE.TOTAL_STAMP
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getTotalStamp() {
        return totalStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TOTAL_STAMP
     *
     * @param totalStamp the value for TB_INVOICE.TOTAL_STAMP
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTotalStamp(BigDecimal totalStamp) {
        this.totalStamp = totalStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TOTAL_BPT
     *
     * @return the value of TB_INVOICE.TOTAL_BPT
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getTotalBpt() {
        return totalBpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TOTAL_BPT
     *
     * @param totalBpt the value for TB_INVOICE.TOTAL_BPT
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTotalBpt(BigDecimal totalBpt) {
        this.totalBpt = totalBpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TOTAL_TAX1
     *
     * @return the value of TB_INVOICE.TOTAL_TAX1
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getTotalTax1() {
        return totalTax1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TOTAL_TAX1
     *
     * @param totalTax1 the value for TB_INVOICE.TOTAL_TAX1
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTotalTax1(BigDecimal totalTax1) {
        this.totalTax1 = totalTax1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TOTAL_TAX2
     *
     * @return the value of TB_INVOICE.TOTAL_TAX2
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getTotalTax2() {
        return totalTax2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TOTAL_TAX2
     *
     * @param totalTax2 the value for TB_INVOICE.TOTAL_TAX2
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTotalTax2(BigDecimal totalTax2) {
        this.totalTax2 = totalTax2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TOTAL_TAX3
     *
     * @return the value of TB_INVOICE.TOTAL_TAX3
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getTotalTax3() {
        return totalTax3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TOTAL_TAX3
     *
     * @param totalTax3 the value for TB_INVOICE.TOTAL_TAX3
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTotalTax3(BigDecimal totalTax3) {
        this.totalTax3 = totalTax3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TOTAL_TAX4
     *
     * @return the value of TB_INVOICE.TOTAL_TAX4
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getTotalTax4() {
        return totalTax4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TOTAL_TAX4
     *
     * @param totalTax4 the value for TB_INVOICE.TOTAL_TAX4
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTotalTax4(BigDecimal totalTax4) {
        this.totalTax4 = totalTax4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TOTAL_TAX5
     *
     * @return the value of TB_INVOICE.TOTAL_TAX5
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getTotalTax5() {
        return totalTax5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TOTAL_TAX5
     *
     * @param totalTax5 the value for TB_INVOICE.TOTAL_TAX5
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTotalTax5(BigDecimal totalTax5) {
        this.totalTax5 = totalTax5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TOTAL_TAXABLE_AMOUNT_ORG
     *
     * @return the value of TB_INVOICE.TOTAL_TAXABLE_AMOUNT_ORG
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getTotalTaxableAmountOrg() {
        return totalTaxableAmountOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TOTAL_TAXABLE_AMOUNT_ORG
     *
     * @param totalTaxableAmountOrg the value for TB_INVOICE.TOTAL_TAXABLE_AMOUNT_ORG
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTotalTaxableAmountOrg(BigDecimal totalTaxableAmountOrg) {
        this.totalTaxableAmountOrg = totalTaxableAmountOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TOTAL_TAXABLE_AMOUNT
     *
     * @return the value of TB_INVOICE.TOTAL_TAXABLE_AMOUNT
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getTotalTaxableAmount() {
        return totalTaxableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TOTAL_TAXABLE_AMOUNT
     *
     * @param totalTaxableAmount the value for TB_INVOICE.TOTAL_TAXABLE_AMOUNT
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTotalTaxableAmount(BigDecimal totalTaxableAmount) {
        this.totalTaxableAmount = totalTaxableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TOTAL_TAX_DUE
     *
     * @return the value of TB_INVOICE.TOTAL_TAX_DUE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getTotalTaxDue() {
        return totalTaxDue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TOTAL_TAX_DUE
     *
     * @param totalTaxDue the value for TB_INVOICE.TOTAL_TAX_DUE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTotalTaxDue(BigDecimal totalTaxDue) {
        this.totalTaxDue = totalTaxDue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.TOTAL_ALL
     *
     * @return the value of TB_INVOICE.TOTAL_ALL
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getTotalAll() {
        return totalAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.TOTAL_ALL
     *
     * @param totalAll the value for TB_INVOICE.TOTAL_ALL
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setTotalAll(BigDecimal totalAll) {
        this.totalAll = totalAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.REMARK
     *
     * @return the value of TB_INVOICE.REMARK
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.REMARK
     *
     * @param remark the value for TB_INVOICE.REMARK
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.STATUS
     *
     * @return the value of TB_INVOICE.STATUS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.STATUS
     *
     * @param status the value for TB_INVOICE.STATUS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.NEGATIVE_FLAG
     *
     * @return the value of TB_INVOICE.NEGATIVE_FLAG
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getNegativeFlag() {
        return negativeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.NEGATIVE_FLAG
     *
     * @param negativeFlag the value for TB_INVOICE.NEGATIVE_FLAG
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setNegativeFlag(String negativeFlag) {
        this.negativeFlag = negativeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.DEDUCTION_STATUS
     *
     * @return the value of TB_INVOICE.DEDUCTION_STATUS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getDeductionStatus() {
        return deductionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.DEDUCTION_STATUS
     *
     * @param deductionStatus the value for TB_INVOICE.DEDUCTION_STATUS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setDeductionStatus(String deductionStatus) {
        this.deductionStatus = deductionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.APPLIED_NEGATIVE_TOTAL_AMOUNT
     *
     * @return the value of TB_INVOICE.APPLIED_NEGATIVE_TOTAL_AMOUNT
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public BigDecimal getAppliedNegativeTotalAmount() {
        return appliedNegativeTotalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.APPLIED_NEGATIVE_TOTAL_AMOUNT
     *
     * @param appliedNegativeTotalAmount the value for TB_INVOICE.APPLIED_NEGATIVE_TOTAL_AMOUNT
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setAppliedNegativeTotalAmount(BigDecimal appliedNegativeTotalAmount) {
        this.appliedNegativeTotalAmount = appliedNegativeTotalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.ORG_INVOICE_UID
     *
     * @return the value of TB_INVOICE.ORG_INVOICE_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public Integer getOrgInvoiceUid() {
        return orgInvoiceUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.ORG_INVOICE_UID
     *
     * @param orgInvoiceUid the value for TB_INVOICE.ORG_INVOICE_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setOrgInvoiceUid(Integer orgInvoiceUid) {
        this.orgInvoiceUid = orgInvoiceUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.NEGATIVE_APPRIVAL_USER_ID
     *
     * @return the value of TB_INVOICE.NEGATIVE_APPRIVAL_USER_ID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getNegativeApprivalUserId() {
        return negativeApprivalUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.NEGATIVE_APPRIVAL_USER_ID
     *
     * @param negativeApprivalUserId the value for TB_INVOICE.NEGATIVE_APPRIVAL_USER_ID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setNegativeApprivalUserId(String negativeApprivalUserId) {
        this.negativeApprivalUserId = negativeApprivalUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.NEGATIVE_APPROVAL_REMARK
     *
     * @return the value of TB_INVOICE.NEGATIVE_APPROVAL_REMARK
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getNegativeApprovalRemark() {
        return negativeApprovalRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.NEGATIVE_APPROVAL_REMARK
     *
     * @param negativeApprovalRemark the value for TB_INVOICE.NEGATIVE_APPROVAL_REMARK
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setNegativeApprovalRemark(String negativeApprovalRemark) {
        this.negativeApprovalRemark = negativeApprovalRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.NEGATIVE_APPROVAL_DATETIME
     *
     * @return the value of TB_INVOICE.NEGATIVE_APPROVAL_DATETIME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public Date getNegativeApprovalDatetime() {
        return negativeApprovalDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.NEGATIVE_APPROVAL_DATETIME
     *
     * @param negativeApprovalDatetime the value for TB_INVOICE.NEGATIVE_APPROVAL_DATETIME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setNegativeApprovalDatetime(Date negativeApprovalDatetime) {
        this.negativeApprovalDatetime = negativeApprovalDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVALID_FLAG
     *
     * @return the value of TB_INVOICE.INVALID_FLAG
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getInvalidFlag() {
        return invalidFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVALID_FLAG
     *
     * @param invalidFlag the value for TB_INVOICE.INVALID_FLAG
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvalidFlag(String invalidFlag) {
        this.invalidFlag = invalidFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVALID_DATETIME
     *
     * @return the value of TB_INVOICE.INVALID_DATETIME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public Date getInvalidDatetime() {
        return invalidDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVALID_DATETIME
     *
     * @param invalidDatetime the value for TB_INVOICE.INVALID_DATETIME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvalidDatetime(Date invalidDatetime) {
        this.invalidDatetime = invalidDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVALID_USER_UID
     *
     * @return the value of TB_INVOICE.INVALID_USER_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getInvalidUserUid() {
        return invalidUserUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVALID_USER_UID
     *
     * @param invalidUserUid the value for TB_INVOICE.INVALID_USER_UID
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvalidUserUid(String invalidUserUid) {
        this.invalidUserUid = invalidUserUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVALID_REMARK
     *
     * @return the value of TB_INVOICE.INVALID_REMARK
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getInvalidRemark() {
        return invalidRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVALID_REMARK
     *
     * @param invalidRemark the value for TB_INVOICE.INVALID_REMARK
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvalidRemark(String invalidRemark) {
        this.invalidRemark = invalidRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.IS_RAFFLED
     *
     * @return the value of TB_INVOICE.IS_RAFFLED
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getIsRaffled() {
        return isRaffled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.IS_RAFFLED
     *
     * @param isRaffled the value for TB_INVOICE.IS_RAFFLED
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setIsRaffled(String isRaffled) {
        this.isRaffled = isRaffled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.IS_LUCKY
     *
     * @return the value of TB_INVOICE.IS_LUCKY
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getIsLucky() {
        return isLucky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.IS_LUCKY
     *
     * @param isLucky the value for TB_INVOICE.IS_LUCKY
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setIsLucky(String isLucky) {
        this.isLucky = isLucky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.CASH_DATE
     *
     * @return the value of TB_INVOICE.CASH_DATE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public Date getCashDate() {
        return cashDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.CASH_DATE
     *
     * @param cashDate the value for TB_INVOICE.CASH_DATE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setCashDate(Date cashDate) {
        this.cashDate = cashDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.IS_UPLOADED
     *
     * @return the value of TB_INVOICE.IS_UPLOADED
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getIsUploaded() {
        return isUploaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.IS_UPLOADED
     *
     * @param isUploaded the value for TB_INVOICE.IS_UPLOADED
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setIsUploaded(String isUploaded) {
        this.isUploaded = isUploaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.PRINT_FLAG
     *
     * @return the value of TB_INVOICE.PRINT_FLAG
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getPrintFlag() {
        return printFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.PRINT_FLAG
     *
     * @param printFlag the value for TB_INVOICE.PRINT_FLAG
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setPrintFlag(String printFlag) {
        this.printFlag = printFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.IS_DEDUCTABLE
     *
     * @return the value of TB_INVOICE.IS_DEDUCTABLE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getIsDeductable() {
        return isDeductable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.IS_DEDUCTABLE
     *
     * @param isDeductable the value for TB_INVOICE.IS_DEDUCTABLE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setIsDeductable(String isDeductable) {
        this.isDeductable = isDeductable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.CRT_DATETIME
     *
     * @return the value of TB_INVOICE.CRT_DATETIME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public Date getCrtDatetime() {
        return crtDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.CRT_DATETIME
     *
     * @param crtDatetime the value for TB_INVOICE.CRT_DATETIME
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setCrtDatetime(Date crtDatetime) {
        this.crtDatetime = crtDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.IS_EINVOICE
     *
     * @return the value of TB_INVOICE.IS_EINVOICE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getIsEinvoice() {
        return isEinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.IS_EINVOICE
     *
     * @param isEinvoice the value for TB_INVOICE.IS_EINVOICE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setIsEinvoice(String isEinvoice) {
        this.isEinvoice = isEinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVOICE_PROCESS_STATUS
     *
     * @return the value of TB_INVOICE.INVOICE_PROCESS_STATUS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getInvoiceProcessStatus() {
        return invoiceProcessStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVOICE_PROCESS_STATUS
     *
     * @param invoiceProcessStatus the value for TB_INVOICE.INVOICE_PROCESS_STATUS
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvoiceProcessStatus(String invoiceProcessStatus) {
        this.invoiceProcessStatus = invoiceProcessStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.INVOICE_REQUEST_TYPE
     *
     * @return the value of TB_INVOICE.INVOICE_REQUEST_TYPE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getInvoiceRequestType() {
        return invoiceRequestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.INVOICE_REQUEST_TYPE
     *
     * @param invoiceRequestType the value for TB_INVOICE.INVOICE_REQUEST_TYPE
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setInvoiceRequestType(String invoiceRequestType) {
        this.invoiceRequestType = invoiceRequestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_INVOICE.SIGN
     *
     * @return the value of TB_INVOICE.SIGN
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_INVOICE.SIGN
     *
     * @param sign the value for TB_INVOICE.SIGN
     *
     * @mbg.generated Tue May 01 17:23:13 CST 2018
     */
    public void setSign(String sign) {
        this.sign = sign;
    }
}