package com.zy.study.bootstudy.entity1;

import java.math.BigDecimal;
import java.util.Date;

public class TbTaxpayer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.TAXPAYER_UID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private BigDecimal taxpayerUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.NAME_IN_ENGLISH
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String nameInEnglish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.NAME_IN_SECOND_LANG
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String nameInSecondLang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.TIN
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String tin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.BRANCH_ID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private BigDecimal branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.TAXPAYER_CATEGORY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String taxpayerCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.TAXPAYER_TYPE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String taxpayerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.REGISTERED_MAGISTERIAL_STATE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String registeredMagisterialState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.TIN_OFFICE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String tinOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.STATE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.CITY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.LOCALITY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String locality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.ID_TYPE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.ID_NUMBER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.TELPHONE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.PHYSICAL_ADDRESS
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String physicalAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.POSTAL_ADDRESS
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String postalAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.MAIN_TAXPABLE_ACTIVITY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String mainTaxpableActivity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.PREFERRED_LANGUAGE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String preferredLanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.REGISTRATION_OFFICE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String registrationOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.SYS_REGISTERED_TIME
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private Date sysRegisteredTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.TURNOVERSIZE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String turnoversize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.ENTERPRISE_SCALE_UID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private BigDecimal enterpriseScaleUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.TAXPAYER_TYPE_UID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private BigDecimal taxpayerTypeUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.INDUSTRY_UID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private BigDecimal industryUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.IS_COMPLETED
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String isCompleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.ALLOW_FOREIGN_CURRENCY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String allowForeignCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.STATUS
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.IS_DELETED
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.REG_ORG_ID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String regOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.CRT_DATETIME
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private Date crtDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.INSERT_USER_ID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String insertUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.LAST_MOD_DATETIME
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private Date lastModDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.LAST_MOD_USER_ID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String lastModUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.TIN_OFFICE_IN_SEC
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String tinOfficeInSec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TAXPAYER.TIN_OFFICE_IN_ENG
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    private String tinOfficeInEng;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.TAXPAYER_UID
     *
     * @return the value of TB_TAXPAYER.TAXPAYER_UID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public BigDecimal getTaxpayerUid() {
        return taxpayerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.TAXPAYER_UID
     *
     * @param taxpayerUid the value for TB_TAXPAYER.TAXPAYER_UID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setTaxpayerUid(BigDecimal taxpayerUid) {
        this.taxpayerUid = taxpayerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.NAME_IN_ENGLISH
     *
     * @return the value of TB_TAXPAYER.NAME_IN_ENGLISH
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getNameInEnglish() {
        return nameInEnglish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.NAME_IN_ENGLISH
     *
     * @param nameInEnglish the value for TB_TAXPAYER.NAME_IN_ENGLISH
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setNameInEnglish(String nameInEnglish) {
        this.nameInEnglish = nameInEnglish == null ? null : nameInEnglish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.NAME_IN_SECOND_LANG
     *
     * @return the value of TB_TAXPAYER.NAME_IN_SECOND_LANG
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getNameInSecondLang() {
        return nameInSecondLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.NAME_IN_SECOND_LANG
     *
     * @param nameInSecondLang the value for TB_TAXPAYER.NAME_IN_SECOND_LANG
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setNameInSecondLang(String nameInSecondLang) {
        this.nameInSecondLang = nameInSecondLang == null ? null : nameInSecondLang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.TIN
     *
     * @return the value of TB_TAXPAYER.TIN
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getTin() {
        return tin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.TIN
     *
     * @param tin the value for TB_TAXPAYER.TIN
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setTin(String tin) {
        this.tin = tin == null ? null : tin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.BRANCH_ID
     *
     * @return the value of TB_TAXPAYER.BRANCH_ID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public BigDecimal getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.BRANCH_ID
     *
     * @param branchId the value for TB_TAXPAYER.BRANCH_ID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setBranchId(BigDecimal branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.TAXPAYER_CATEGORY
     *
     * @return the value of TB_TAXPAYER.TAXPAYER_CATEGORY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getTaxpayerCategory() {
        return taxpayerCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.TAXPAYER_CATEGORY
     *
     * @param taxpayerCategory the value for TB_TAXPAYER.TAXPAYER_CATEGORY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setTaxpayerCategory(String taxpayerCategory) {
        this.taxpayerCategory = taxpayerCategory == null ? null : taxpayerCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.TAXPAYER_TYPE
     *
     * @return the value of TB_TAXPAYER.TAXPAYER_TYPE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getTaxpayerType() {
        return taxpayerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.TAXPAYER_TYPE
     *
     * @param taxpayerType the value for TB_TAXPAYER.TAXPAYER_TYPE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setTaxpayerType(String taxpayerType) {
        this.taxpayerType = taxpayerType == null ? null : taxpayerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.REGISTERED_MAGISTERIAL_STATE
     *
     * @return the value of TB_TAXPAYER.REGISTERED_MAGISTERIAL_STATE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getRegisteredMagisterialState() {
        return registeredMagisterialState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.REGISTERED_MAGISTERIAL_STATE
     *
     * @param registeredMagisterialState the value for TB_TAXPAYER.REGISTERED_MAGISTERIAL_STATE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setRegisteredMagisterialState(String registeredMagisterialState) {
        this.registeredMagisterialState = registeredMagisterialState == null ? null : registeredMagisterialState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.TIN_OFFICE
     *
     * @return the value of TB_TAXPAYER.TIN_OFFICE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getTinOffice() {
        return tinOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.TIN_OFFICE
     *
     * @param tinOffice the value for TB_TAXPAYER.TIN_OFFICE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setTinOffice(String tinOffice) {
        this.tinOffice = tinOffice == null ? null : tinOffice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.STATE
     *
     * @return the value of TB_TAXPAYER.STATE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.STATE
     *
     * @param state the value for TB_TAXPAYER.STATE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.CITY
     *
     * @return the value of TB_TAXPAYER.CITY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.CITY
     *
     * @param city the value for TB_TAXPAYER.CITY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.LOCALITY
     *
     * @return the value of TB_TAXPAYER.LOCALITY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getLocality() {
        return locality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.LOCALITY
     *
     * @param locality the value for TB_TAXPAYER.LOCALITY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setLocality(String locality) {
        this.locality = locality == null ? null : locality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.ID_TYPE
     *
     * @return the value of TB_TAXPAYER.ID_TYPE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.ID_TYPE
     *
     * @param idType the value for TB_TAXPAYER.ID_TYPE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setIdType(String idType) {
        this.idType = idType == null ? null : idType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.ID_NUMBER
     *
     * @return the value of TB_TAXPAYER.ID_NUMBER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.ID_NUMBER
     *
     * @param idNumber the value for TB_TAXPAYER.ID_NUMBER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.TELPHONE
     *
     * @return the value of TB_TAXPAYER.TELPHONE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.TELPHONE
     *
     * @param telphone the value for TB_TAXPAYER.TELPHONE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.PHYSICAL_ADDRESS
     *
     * @return the value of TB_TAXPAYER.PHYSICAL_ADDRESS
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getPhysicalAddress() {
        return physicalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.PHYSICAL_ADDRESS
     *
     * @param physicalAddress the value for TB_TAXPAYER.PHYSICAL_ADDRESS
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setPhysicalAddress(String physicalAddress) {
        this.physicalAddress = physicalAddress == null ? null : physicalAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.POSTAL_ADDRESS
     *
     * @return the value of TB_TAXPAYER.POSTAL_ADDRESS
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getPostalAddress() {
        return postalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.POSTAL_ADDRESS
     *
     * @param postalAddress the value for TB_TAXPAYER.POSTAL_ADDRESS
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setPostalAddress(String postalAddress) {
        this.postalAddress = postalAddress == null ? null : postalAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.MAIN_TAXPABLE_ACTIVITY
     *
     * @return the value of TB_TAXPAYER.MAIN_TAXPABLE_ACTIVITY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getMainTaxpableActivity() {
        return mainTaxpableActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.MAIN_TAXPABLE_ACTIVITY
     *
     * @param mainTaxpableActivity the value for TB_TAXPAYER.MAIN_TAXPABLE_ACTIVITY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setMainTaxpableActivity(String mainTaxpableActivity) {
        this.mainTaxpableActivity = mainTaxpableActivity == null ? null : mainTaxpableActivity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.PREFERRED_LANGUAGE
     *
     * @return the value of TB_TAXPAYER.PREFERRED_LANGUAGE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getPreferredLanguage() {
        return preferredLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.PREFERRED_LANGUAGE
     *
     * @param preferredLanguage the value for TB_TAXPAYER.PREFERRED_LANGUAGE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setPreferredLanguage(String preferredLanguage) {
        this.preferredLanguage = preferredLanguage == null ? null : preferredLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.REGISTRATION_OFFICE
     *
     * @return the value of TB_TAXPAYER.REGISTRATION_OFFICE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getRegistrationOffice() {
        return registrationOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.REGISTRATION_OFFICE
     *
     * @param registrationOffice the value for TB_TAXPAYER.REGISTRATION_OFFICE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setRegistrationOffice(String registrationOffice) {
        this.registrationOffice = registrationOffice == null ? null : registrationOffice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.SYS_REGISTERED_TIME
     *
     * @return the value of TB_TAXPAYER.SYS_REGISTERED_TIME
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public Date getSysRegisteredTime() {
        return sysRegisteredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.SYS_REGISTERED_TIME
     *
     * @param sysRegisteredTime the value for TB_TAXPAYER.SYS_REGISTERED_TIME
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setSysRegisteredTime(Date sysRegisteredTime) {
        this.sysRegisteredTime = sysRegisteredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.TURNOVERSIZE
     *
     * @return the value of TB_TAXPAYER.TURNOVERSIZE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getTurnoversize() {
        return turnoversize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.TURNOVERSIZE
     *
     * @param turnoversize the value for TB_TAXPAYER.TURNOVERSIZE
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setTurnoversize(String turnoversize) {
        this.turnoversize = turnoversize == null ? null : turnoversize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.ENTERPRISE_SCALE_UID
     *
     * @return the value of TB_TAXPAYER.ENTERPRISE_SCALE_UID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public BigDecimal getEnterpriseScaleUid() {
        return enterpriseScaleUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.ENTERPRISE_SCALE_UID
     *
     * @param enterpriseScaleUid the value for TB_TAXPAYER.ENTERPRISE_SCALE_UID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setEnterpriseScaleUid(BigDecimal enterpriseScaleUid) {
        this.enterpriseScaleUid = enterpriseScaleUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.TAXPAYER_TYPE_UID
     *
     * @return the value of TB_TAXPAYER.TAXPAYER_TYPE_UID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public BigDecimal getTaxpayerTypeUid() {
        return taxpayerTypeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.TAXPAYER_TYPE_UID
     *
     * @param taxpayerTypeUid the value for TB_TAXPAYER.TAXPAYER_TYPE_UID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setTaxpayerTypeUid(BigDecimal taxpayerTypeUid) {
        this.taxpayerTypeUid = taxpayerTypeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.INDUSTRY_UID
     *
     * @return the value of TB_TAXPAYER.INDUSTRY_UID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public BigDecimal getIndustryUid() {
        return industryUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.INDUSTRY_UID
     *
     * @param industryUid the value for TB_TAXPAYER.INDUSTRY_UID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setIndustryUid(BigDecimal industryUid) {
        this.industryUid = industryUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.IS_COMPLETED
     *
     * @return the value of TB_TAXPAYER.IS_COMPLETED
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getIsCompleted() {
        return isCompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.IS_COMPLETED
     *
     * @param isCompleted the value for TB_TAXPAYER.IS_COMPLETED
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setIsCompleted(String isCompleted) {
        this.isCompleted = isCompleted == null ? null : isCompleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.ALLOW_FOREIGN_CURRENCY
     *
     * @return the value of TB_TAXPAYER.ALLOW_FOREIGN_CURRENCY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getAllowForeignCurrency() {
        return allowForeignCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.ALLOW_FOREIGN_CURRENCY
     *
     * @param allowForeignCurrency the value for TB_TAXPAYER.ALLOW_FOREIGN_CURRENCY
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setAllowForeignCurrency(String allowForeignCurrency) {
        this.allowForeignCurrency = allowForeignCurrency == null ? null : allowForeignCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.STATUS
     *
     * @return the value of TB_TAXPAYER.STATUS
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.STATUS
     *
     * @param status the value for TB_TAXPAYER.STATUS
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.IS_DELETED
     *
     * @return the value of TB_TAXPAYER.IS_DELETED
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.IS_DELETED
     *
     * @param isDeleted the value for TB_TAXPAYER.IS_DELETED
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.REG_ORG_ID
     *
     * @return the value of TB_TAXPAYER.REG_ORG_ID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getRegOrgId() {
        return regOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.REG_ORG_ID
     *
     * @param regOrgId the value for TB_TAXPAYER.REG_ORG_ID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setRegOrgId(String regOrgId) {
        this.regOrgId = regOrgId == null ? null : regOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.CRT_DATETIME
     *
     * @return the value of TB_TAXPAYER.CRT_DATETIME
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public Date getCrtDatetime() {
        return crtDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.CRT_DATETIME
     *
     * @param crtDatetime the value for TB_TAXPAYER.CRT_DATETIME
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setCrtDatetime(Date crtDatetime) {
        this.crtDatetime = crtDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.INSERT_USER_ID
     *
     * @return the value of TB_TAXPAYER.INSERT_USER_ID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.INSERT_USER_ID
     *
     * @param insertUserId the value for TB_TAXPAYER.INSERT_USER_ID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.LAST_MOD_DATETIME
     *
     * @return the value of TB_TAXPAYER.LAST_MOD_DATETIME
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public Date getLastModDatetime() {
        return lastModDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.LAST_MOD_DATETIME
     *
     * @param lastModDatetime the value for TB_TAXPAYER.LAST_MOD_DATETIME
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setLastModDatetime(Date lastModDatetime) {
        this.lastModDatetime = lastModDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.LAST_MOD_USER_ID
     *
     * @return the value of TB_TAXPAYER.LAST_MOD_USER_ID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getLastModUserId() {
        return lastModUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.LAST_MOD_USER_ID
     *
     * @param lastModUserId the value for TB_TAXPAYER.LAST_MOD_USER_ID
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setLastModUserId(String lastModUserId) {
        this.lastModUserId = lastModUserId == null ? null : lastModUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.TIN_OFFICE_IN_SEC
     *
     * @return the value of TB_TAXPAYER.TIN_OFFICE_IN_SEC
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getTinOfficeInSec() {
        return tinOfficeInSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.TIN_OFFICE_IN_SEC
     *
     * @param tinOfficeInSec the value for TB_TAXPAYER.TIN_OFFICE_IN_SEC
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setTinOfficeInSec(String tinOfficeInSec) {
        this.tinOfficeInSec = tinOfficeInSec == null ? null : tinOfficeInSec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TAXPAYER.TIN_OFFICE_IN_ENG
     *
     * @return the value of TB_TAXPAYER.TIN_OFFICE_IN_ENG
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getTinOfficeInEng() {
        return tinOfficeInEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TAXPAYER.TIN_OFFICE_IN_ENG
     *
     * @param tinOfficeInEng the value for TB_TAXPAYER.TIN_OFFICE_IN_ENG
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setTinOfficeInEng(String tinOfficeInEng) {
        this.tinOfficeInEng = tinOfficeInEng == null ? null : tinOfficeInEng.trim();
    }
}