package com.zy.study.bootstudy.entity1;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbTaxpayerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public TbTaxpayerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaxpayerUidIsNull() {
            addCriterion("TAXPAYER_UID is null");
            return (Criteria) this;
        }

        public Criteria andTaxpayerUidIsNotNull() {
            addCriterion("TAXPAYER_UID is not null");
            return (Criteria) this;
        }

        public Criteria andTaxpayerUidEqualTo(BigDecimal value) {
            addCriterion("TAXPAYER_UID =", value, "taxpayerUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerUidNotEqualTo(BigDecimal value) {
            addCriterion("TAXPAYER_UID <>", value, "taxpayerUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerUidGreaterThan(BigDecimal value) {
            addCriterion("TAXPAYER_UID >", value, "taxpayerUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerUidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TAXPAYER_UID >=", value, "taxpayerUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerUidLessThan(BigDecimal value) {
            addCriterion("TAXPAYER_UID <", value, "taxpayerUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerUidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TAXPAYER_UID <=", value, "taxpayerUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerUidIn(List<BigDecimal> values) {
            addCriterion("TAXPAYER_UID in", values, "taxpayerUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerUidNotIn(List<BigDecimal> values) {
            addCriterion("TAXPAYER_UID not in", values, "taxpayerUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerUidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TAXPAYER_UID between", value1, value2, "taxpayerUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerUidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TAXPAYER_UID not between", value1, value2, "taxpayerUid");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishIsNull() {
            addCriterion("NAME_IN_ENGLISH is null");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishIsNotNull() {
            addCriterion("NAME_IN_ENGLISH is not null");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishEqualTo(String value) {
            addCriterion("NAME_IN_ENGLISH =", value, "nameInEnglish");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishNotEqualTo(String value) {
            addCriterion("NAME_IN_ENGLISH <>", value, "nameInEnglish");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishGreaterThan(String value) {
            addCriterion("NAME_IN_ENGLISH >", value, "nameInEnglish");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishGreaterThanOrEqualTo(String value) {
            addCriterion("NAME_IN_ENGLISH >=", value, "nameInEnglish");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishLessThan(String value) {
            addCriterion("NAME_IN_ENGLISH <", value, "nameInEnglish");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishLessThanOrEqualTo(String value) {
            addCriterion("NAME_IN_ENGLISH <=", value, "nameInEnglish");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishLike(String value) {
            addCriterion("NAME_IN_ENGLISH like", value, "nameInEnglish");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishNotLike(String value) {
            addCriterion("NAME_IN_ENGLISH not like", value, "nameInEnglish");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishIn(List<String> values) {
            addCriterion("NAME_IN_ENGLISH in", values, "nameInEnglish");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishNotIn(List<String> values) {
            addCriterion("NAME_IN_ENGLISH not in", values, "nameInEnglish");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishBetween(String value1, String value2) {
            addCriterion("NAME_IN_ENGLISH between", value1, value2, "nameInEnglish");
            return (Criteria) this;
        }

        public Criteria andNameInEnglishNotBetween(String value1, String value2) {
            addCriterion("NAME_IN_ENGLISH not between", value1, value2, "nameInEnglish");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangIsNull() {
            addCriterion("NAME_IN_SECOND_LANG is null");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangIsNotNull() {
            addCriterion("NAME_IN_SECOND_LANG is not null");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangEqualTo(String value) {
            addCriterion("NAME_IN_SECOND_LANG =", value, "nameInSecondLang");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangNotEqualTo(String value) {
            addCriterion("NAME_IN_SECOND_LANG <>", value, "nameInSecondLang");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangGreaterThan(String value) {
            addCriterion("NAME_IN_SECOND_LANG >", value, "nameInSecondLang");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangGreaterThanOrEqualTo(String value) {
            addCriterion("NAME_IN_SECOND_LANG >=", value, "nameInSecondLang");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangLessThan(String value) {
            addCriterion("NAME_IN_SECOND_LANG <", value, "nameInSecondLang");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangLessThanOrEqualTo(String value) {
            addCriterion("NAME_IN_SECOND_LANG <=", value, "nameInSecondLang");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangLike(String value) {
            addCriterion("NAME_IN_SECOND_LANG like", value, "nameInSecondLang");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangNotLike(String value) {
            addCriterion("NAME_IN_SECOND_LANG not like", value, "nameInSecondLang");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangIn(List<String> values) {
            addCriterion("NAME_IN_SECOND_LANG in", values, "nameInSecondLang");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangNotIn(List<String> values) {
            addCriterion("NAME_IN_SECOND_LANG not in", values, "nameInSecondLang");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangBetween(String value1, String value2) {
            addCriterion("NAME_IN_SECOND_LANG between", value1, value2, "nameInSecondLang");
            return (Criteria) this;
        }

        public Criteria andNameInSecondLangNotBetween(String value1, String value2) {
            addCriterion("NAME_IN_SECOND_LANG not between", value1, value2, "nameInSecondLang");
            return (Criteria) this;
        }

        public Criteria andTinIsNull() {
            addCriterion("TIN is null");
            return (Criteria) this;
        }

        public Criteria andTinIsNotNull() {
            addCriterion("TIN is not null");
            return (Criteria) this;
        }

        public Criteria andTinEqualTo(String value) {
            addCriterion("TIN =", value, "tin");
            return (Criteria) this;
        }

        public Criteria andTinNotEqualTo(String value) {
            addCriterion("TIN <>", value, "tin");
            return (Criteria) this;
        }

        public Criteria andTinGreaterThan(String value) {
            addCriterion("TIN >", value, "tin");
            return (Criteria) this;
        }

        public Criteria andTinGreaterThanOrEqualTo(String value) {
            addCriterion("TIN >=", value, "tin");
            return (Criteria) this;
        }

        public Criteria andTinLessThan(String value) {
            addCriterion("TIN <", value, "tin");
            return (Criteria) this;
        }

        public Criteria andTinLessThanOrEqualTo(String value) {
            addCriterion("TIN <=", value, "tin");
            return (Criteria) this;
        }

        public Criteria andTinLike(String value) {
            addCriterion("TIN like", value, "tin");
            return (Criteria) this;
        }

        public Criteria andTinNotLike(String value) {
            addCriterion("TIN not like", value, "tin");
            return (Criteria) this;
        }

        public Criteria andTinIn(List<String> values) {
            addCriterion("TIN in", values, "tin");
            return (Criteria) this;
        }

        public Criteria andTinNotIn(List<String> values) {
            addCriterion("TIN not in", values, "tin");
            return (Criteria) this;
        }

        public Criteria andTinBetween(String value1, String value2) {
            addCriterion("TIN between", value1, value2, "tin");
            return (Criteria) this;
        }

        public Criteria andTinNotBetween(String value1, String value2) {
            addCriterion("TIN not between", value1, value2, "tin");
            return (Criteria) this;
        }

        public Criteria andBranchIdIsNull() {
            addCriterion("BRANCH_ID is null");
            return (Criteria) this;
        }

        public Criteria andBranchIdIsNotNull() {
            addCriterion("BRANCH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBranchIdEqualTo(BigDecimal value) {
            addCriterion("BRANCH_ID =", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotEqualTo(BigDecimal value) {
            addCriterion("BRANCH_ID <>", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdGreaterThan(BigDecimal value) {
            addCriterion("BRANCH_ID >", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BRANCH_ID >=", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLessThan(BigDecimal value) {
            addCriterion("BRANCH_ID <", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BRANCH_ID <=", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdIn(List<BigDecimal> values) {
            addCriterion("BRANCH_ID in", values, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotIn(List<BigDecimal> values) {
            addCriterion("BRANCH_ID not in", values, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BRANCH_ID between", value1, value2, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BRANCH_ID not between", value1, value2, "branchId");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryIsNull() {
            addCriterion("TAXPAYER_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryIsNotNull() {
            addCriterion("TAXPAYER_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryEqualTo(String value) {
            addCriterion("TAXPAYER_CATEGORY =", value, "taxpayerCategory");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryNotEqualTo(String value) {
            addCriterion("TAXPAYER_CATEGORY <>", value, "taxpayerCategory");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryGreaterThan(String value) {
            addCriterion("TAXPAYER_CATEGORY >", value, "taxpayerCategory");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("TAXPAYER_CATEGORY >=", value, "taxpayerCategory");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryLessThan(String value) {
            addCriterion("TAXPAYER_CATEGORY <", value, "taxpayerCategory");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryLessThanOrEqualTo(String value) {
            addCriterion("TAXPAYER_CATEGORY <=", value, "taxpayerCategory");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryLike(String value) {
            addCriterion("TAXPAYER_CATEGORY like", value, "taxpayerCategory");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryNotLike(String value) {
            addCriterion("TAXPAYER_CATEGORY not like", value, "taxpayerCategory");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryIn(List<String> values) {
            addCriterion("TAXPAYER_CATEGORY in", values, "taxpayerCategory");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryNotIn(List<String> values) {
            addCriterion("TAXPAYER_CATEGORY not in", values, "taxpayerCategory");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryBetween(String value1, String value2) {
            addCriterion("TAXPAYER_CATEGORY between", value1, value2, "taxpayerCategory");
            return (Criteria) this;
        }

        public Criteria andTaxpayerCategoryNotBetween(String value1, String value2) {
            addCriterion("TAXPAYER_CATEGORY not between", value1, value2, "taxpayerCategory");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeIsNull() {
            addCriterion("TAXPAYER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeIsNotNull() {
            addCriterion("TAXPAYER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeEqualTo(String value) {
            addCriterion("TAXPAYER_TYPE =", value, "taxpayerType");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeNotEqualTo(String value) {
            addCriterion("TAXPAYER_TYPE <>", value, "taxpayerType");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeGreaterThan(String value) {
            addCriterion("TAXPAYER_TYPE >", value, "taxpayerType");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TAXPAYER_TYPE >=", value, "taxpayerType");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeLessThan(String value) {
            addCriterion("TAXPAYER_TYPE <", value, "taxpayerType");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeLessThanOrEqualTo(String value) {
            addCriterion("TAXPAYER_TYPE <=", value, "taxpayerType");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeLike(String value) {
            addCriterion("TAXPAYER_TYPE like", value, "taxpayerType");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeNotLike(String value) {
            addCriterion("TAXPAYER_TYPE not like", value, "taxpayerType");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeIn(List<String> values) {
            addCriterion("TAXPAYER_TYPE in", values, "taxpayerType");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeNotIn(List<String> values) {
            addCriterion("TAXPAYER_TYPE not in", values, "taxpayerType");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeBetween(String value1, String value2) {
            addCriterion("TAXPAYER_TYPE between", value1, value2, "taxpayerType");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeNotBetween(String value1, String value2) {
            addCriterion("TAXPAYER_TYPE not between", value1, value2, "taxpayerType");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateIsNull() {
            addCriterion("REGISTERED_MAGISTERIAL_STATE is null");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateIsNotNull() {
            addCriterion("REGISTERED_MAGISTERIAL_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateEqualTo(String value) {
            addCriterion("REGISTERED_MAGISTERIAL_STATE =", value, "registeredMagisterialState");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateNotEqualTo(String value) {
            addCriterion("REGISTERED_MAGISTERIAL_STATE <>", value, "registeredMagisterialState");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateGreaterThan(String value) {
            addCriterion("REGISTERED_MAGISTERIAL_STATE >", value, "registeredMagisterialState");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateGreaterThanOrEqualTo(String value) {
            addCriterion("REGISTERED_MAGISTERIAL_STATE >=", value, "registeredMagisterialState");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateLessThan(String value) {
            addCriterion("REGISTERED_MAGISTERIAL_STATE <", value, "registeredMagisterialState");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateLessThanOrEqualTo(String value) {
            addCriterion("REGISTERED_MAGISTERIAL_STATE <=", value, "registeredMagisterialState");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateLike(String value) {
            addCriterion("REGISTERED_MAGISTERIAL_STATE like", value, "registeredMagisterialState");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateNotLike(String value) {
            addCriterion("REGISTERED_MAGISTERIAL_STATE not like", value, "registeredMagisterialState");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateIn(List<String> values) {
            addCriterion("REGISTERED_MAGISTERIAL_STATE in", values, "registeredMagisterialState");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateNotIn(List<String> values) {
            addCriterion("REGISTERED_MAGISTERIAL_STATE not in", values, "registeredMagisterialState");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateBetween(String value1, String value2) {
            addCriterion("REGISTERED_MAGISTERIAL_STATE between", value1, value2, "registeredMagisterialState");
            return (Criteria) this;
        }

        public Criteria andRegisteredMagisterialStateNotBetween(String value1, String value2) {
            addCriterion("REGISTERED_MAGISTERIAL_STATE not between", value1, value2, "registeredMagisterialState");
            return (Criteria) this;
        }

        public Criteria andTinOfficeIsNull() {
            addCriterion("TIN_OFFICE is null");
            return (Criteria) this;
        }

        public Criteria andTinOfficeIsNotNull() {
            addCriterion("TIN_OFFICE is not null");
            return (Criteria) this;
        }

        public Criteria andTinOfficeEqualTo(String value) {
            addCriterion("TIN_OFFICE =", value, "tinOffice");
            return (Criteria) this;
        }

        public Criteria andTinOfficeNotEqualTo(String value) {
            addCriterion("TIN_OFFICE <>", value, "tinOffice");
            return (Criteria) this;
        }

        public Criteria andTinOfficeGreaterThan(String value) {
            addCriterion("TIN_OFFICE >", value, "tinOffice");
            return (Criteria) this;
        }

        public Criteria andTinOfficeGreaterThanOrEqualTo(String value) {
            addCriterion("TIN_OFFICE >=", value, "tinOffice");
            return (Criteria) this;
        }

        public Criteria andTinOfficeLessThan(String value) {
            addCriterion("TIN_OFFICE <", value, "tinOffice");
            return (Criteria) this;
        }

        public Criteria andTinOfficeLessThanOrEqualTo(String value) {
            addCriterion("TIN_OFFICE <=", value, "tinOffice");
            return (Criteria) this;
        }

        public Criteria andTinOfficeLike(String value) {
            addCriterion("TIN_OFFICE like", value, "tinOffice");
            return (Criteria) this;
        }

        public Criteria andTinOfficeNotLike(String value) {
            addCriterion("TIN_OFFICE not like", value, "tinOffice");
            return (Criteria) this;
        }

        public Criteria andTinOfficeIn(List<String> values) {
            addCriterion("TIN_OFFICE in", values, "tinOffice");
            return (Criteria) this;
        }

        public Criteria andTinOfficeNotIn(List<String> values) {
            addCriterion("TIN_OFFICE not in", values, "tinOffice");
            return (Criteria) this;
        }

        public Criteria andTinOfficeBetween(String value1, String value2) {
            addCriterion("TIN_OFFICE between", value1, value2, "tinOffice");
            return (Criteria) this;
        }

        public Criteria andTinOfficeNotBetween(String value1, String value2) {
            addCriterion("TIN_OFFICE not between", value1, value2, "tinOffice");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("CITY is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("CITY is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("CITY =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("CITY <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("CITY >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("CITY >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("CITY <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("CITY <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("CITY like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("CITY not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("CITY in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("CITY not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("CITY between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("CITY not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andLocalityIsNull() {
            addCriterion("LOCALITY is null");
            return (Criteria) this;
        }

        public Criteria andLocalityIsNotNull() {
            addCriterion("LOCALITY is not null");
            return (Criteria) this;
        }

        public Criteria andLocalityEqualTo(String value) {
            addCriterion("LOCALITY =", value, "locality");
            return (Criteria) this;
        }

        public Criteria andLocalityNotEqualTo(String value) {
            addCriterion("LOCALITY <>", value, "locality");
            return (Criteria) this;
        }

        public Criteria andLocalityGreaterThan(String value) {
            addCriterion("LOCALITY >", value, "locality");
            return (Criteria) this;
        }

        public Criteria andLocalityGreaterThanOrEqualTo(String value) {
            addCriterion("LOCALITY >=", value, "locality");
            return (Criteria) this;
        }

        public Criteria andLocalityLessThan(String value) {
            addCriterion("LOCALITY <", value, "locality");
            return (Criteria) this;
        }

        public Criteria andLocalityLessThanOrEqualTo(String value) {
            addCriterion("LOCALITY <=", value, "locality");
            return (Criteria) this;
        }

        public Criteria andLocalityLike(String value) {
            addCriterion("LOCALITY like", value, "locality");
            return (Criteria) this;
        }

        public Criteria andLocalityNotLike(String value) {
            addCriterion("LOCALITY not like", value, "locality");
            return (Criteria) this;
        }

        public Criteria andLocalityIn(List<String> values) {
            addCriterion("LOCALITY in", values, "locality");
            return (Criteria) this;
        }

        public Criteria andLocalityNotIn(List<String> values) {
            addCriterion("LOCALITY not in", values, "locality");
            return (Criteria) this;
        }

        public Criteria andLocalityBetween(String value1, String value2) {
            addCriterion("LOCALITY between", value1, value2, "locality");
            return (Criteria) this;
        }

        public Criteria andLocalityNotBetween(String value1, String value2) {
            addCriterion("LOCALITY not between", value1, value2, "locality");
            return (Criteria) this;
        }

        public Criteria andIdTypeIsNull() {
            addCriterion("ID_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andIdTypeIsNotNull() {
            addCriterion("ID_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andIdTypeEqualTo(String value) {
            addCriterion("ID_TYPE =", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotEqualTo(String value) {
            addCriterion("ID_TYPE <>", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeGreaterThan(String value) {
            addCriterion("ID_TYPE >", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ID_TYPE >=", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeLessThan(String value) {
            addCriterion("ID_TYPE <", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeLessThanOrEqualTo(String value) {
            addCriterion("ID_TYPE <=", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeLike(String value) {
            addCriterion("ID_TYPE like", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotLike(String value) {
            addCriterion("ID_TYPE not like", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeIn(List<String> values) {
            addCriterion("ID_TYPE in", values, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotIn(List<String> values) {
            addCriterion("ID_TYPE not in", values, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeBetween(String value1, String value2) {
            addCriterion("ID_TYPE between", value1, value2, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotBetween(String value1, String value2) {
            addCriterion("ID_TYPE not between", value1, value2, "idType");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNull() {
            addCriterion("ID_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNotNull() {
            addCriterion("ID_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andIdNumberEqualTo(String value) {
            addCriterion("ID_NUMBER =", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotEqualTo(String value) {
            addCriterion("ID_NUMBER <>", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThan(String value) {
            addCriterion("ID_NUMBER >", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThanOrEqualTo(String value) {
            addCriterion("ID_NUMBER >=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThan(String value) {
            addCriterion("ID_NUMBER <", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThanOrEqualTo(String value) {
            addCriterion("ID_NUMBER <=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLike(String value) {
            addCriterion("ID_NUMBER like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotLike(String value) {
            addCriterion("ID_NUMBER not like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberIn(List<String> values) {
            addCriterion("ID_NUMBER in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotIn(List<String> values) {
            addCriterion("ID_NUMBER not in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberBetween(String value1, String value2) {
            addCriterion("ID_NUMBER between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotBetween(String value1, String value2) {
            addCriterion("ID_NUMBER not between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andTelphoneIsNull() {
            addCriterion("TELPHONE is null");
            return (Criteria) this;
        }

        public Criteria andTelphoneIsNotNull() {
            addCriterion("TELPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andTelphoneEqualTo(String value) {
            addCriterion("TELPHONE =", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotEqualTo(String value) {
            addCriterion("TELPHONE <>", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneGreaterThan(String value) {
            addCriterion("TELPHONE >", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneGreaterThanOrEqualTo(String value) {
            addCriterion("TELPHONE >=", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLessThan(String value) {
            addCriterion("TELPHONE <", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLessThanOrEqualTo(String value) {
            addCriterion("TELPHONE <=", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLike(String value) {
            addCriterion("TELPHONE like", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotLike(String value) {
            addCriterion("TELPHONE not like", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneIn(List<String> values) {
            addCriterion("TELPHONE in", values, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotIn(List<String> values) {
            addCriterion("TELPHONE not in", values, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneBetween(String value1, String value2) {
            addCriterion("TELPHONE between", value1, value2, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotBetween(String value1, String value2) {
            addCriterion("TELPHONE not between", value1, value2, "telphone");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressIsNull() {
            addCriterion("PHYSICAL_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressIsNotNull() {
            addCriterion("PHYSICAL_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressEqualTo(String value) {
            addCriterion("PHYSICAL_ADDRESS =", value, "physicalAddress");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressNotEqualTo(String value) {
            addCriterion("PHYSICAL_ADDRESS <>", value, "physicalAddress");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressGreaterThan(String value) {
            addCriterion("PHYSICAL_ADDRESS >", value, "physicalAddress");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressGreaterThanOrEqualTo(String value) {
            addCriterion("PHYSICAL_ADDRESS >=", value, "physicalAddress");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressLessThan(String value) {
            addCriterion("PHYSICAL_ADDRESS <", value, "physicalAddress");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressLessThanOrEqualTo(String value) {
            addCriterion("PHYSICAL_ADDRESS <=", value, "physicalAddress");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressLike(String value) {
            addCriterion("PHYSICAL_ADDRESS like", value, "physicalAddress");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressNotLike(String value) {
            addCriterion("PHYSICAL_ADDRESS not like", value, "physicalAddress");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressIn(List<String> values) {
            addCriterion("PHYSICAL_ADDRESS in", values, "physicalAddress");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressNotIn(List<String> values) {
            addCriterion("PHYSICAL_ADDRESS not in", values, "physicalAddress");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressBetween(String value1, String value2) {
            addCriterion("PHYSICAL_ADDRESS between", value1, value2, "physicalAddress");
            return (Criteria) this;
        }

        public Criteria andPhysicalAddressNotBetween(String value1, String value2) {
            addCriterion("PHYSICAL_ADDRESS not between", value1, value2, "physicalAddress");
            return (Criteria) this;
        }

        public Criteria andPostalAddressIsNull() {
            addCriterion("POSTAL_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andPostalAddressIsNotNull() {
            addCriterion("POSTAL_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andPostalAddressEqualTo(String value) {
            addCriterion("POSTAL_ADDRESS =", value, "postalAddress");
            return (Criteria) this;
        }

        public Criteria andPostalAddressNotEqualTo(String value) {
            addCriterion("POSTAL_ADDRESS <>", value, "postalAddress");
            return (Criteria) this;
        }

        public Criteria andPostalAddressGreaterThan(String value) {
            addCriterion("POSTAL_ADDRESS >", value, "postalAddress");
            return (Criteria) this;
        }

        public Criteria andPostalAddressGreaterThanOrEqualTo(String value) {
            addCriterion("POSTAL_ADDRESS >=", value, "postalAddress");
            return (Criteria) this;
        }

        public Criteria andPostalAddressLessThan(String value) {
            addCriterion("POSTAL_ADDRESS <", value, "postalAddress");
            return (Criteria) this;
        }

        public Criteria andPostalAddressLessThanOrEqualTo(String value) {
            addCriterion("POSTAL_ADDRESS <=", value, "postalAddress");
            return (Criteria) this;
        }

        public Criteria andPostalAddressLike(String value) {
            addCriterion("POSTAL_ADDRESS like", value, "postalAddress");
            return (Criteria) this;
        }

        public Criteria andPostalAddressNotLike(String value) {
            addCriterion("POSTAL_ADDRESS not like", value, "postalAddress");
            return (Criteria) this;
        }

        public Criteria andPostalAddressIn(List<String> values) {
            addCriterion("POSTAL_ADDRESS in", values, "postalAddress");
            return (Criteria) this;
        }

        public Criteria andPostalAddressNotIn(List<String> values) {
            addCriterion("POSTAL_ADDRESS not in", values, "postalAddress");
            return (Criteria) this;
        }

        public Criteria andPostalAddressBetween(String value1, String value2) {
            addCriterion("POSTAL_ADDRESS between", value1, value2, "postalAddress");
            return (Criteria) this;
        }

        public Criteria andPostalAddressNotBetween(String value1, String value2) {
            addCriterion("POSTAL_ADDRESS not between", value1, value2, "postalAddress");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityIsNull() {
            addCriterion("MAIN_TAXPABLE_ACTIVITY is null");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityIsNotNull() {
            addCriterion("MAIN_TAXPABLE_ACTIVITY is not null");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityEqualTo(String value) {
            addCriterion("MAIN_TAXPABLE_ACTIVITY =", value, "mainTaxpableActivity");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityNotEqualTo(String value) {
            addCriterion("MAIN_TAXPABLE_ACTIVITY <>", value, "mainTaxpableActivity");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityGreaterThan(String value) {
            addCriterion("MAIN_TAXPABLE_ACTIVITY >", value, "mainTaxpableActivity");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityGreaterThanOrEqualTo(String value) {
            addCriterion("MAIN_TAXPABLE_ACTIVITY >=", value, "mainTaxpableActivity");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityLessThan(String value) {
            addCriterion("MAIN_TAXPABLE_ACTIVITY <", value, "mainTaxpableActivity");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityLessThanOrEqualTo(String value) {
            addCriterion("MAIN_TAXPABLE_ACTIVITY <=", value, "mainTaxpableActivity");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityLike(String value) {
            addCriterion("MAIN_TAXPABLE_ACTIVITY like", value, "mainTaxpableActivity");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityNotLike(String value) {
            addCriterion("MAIN_TAXPABLE_ACTIVITY not like", value, "mainTaxpableActivity");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityIn(List<String> values) {
            addCriterion("MAIN_TAXPABLE_ACTIVITY in", values, "mainTaxpableActivity");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityNotIn(List<String> values) {
            addCriterion("MAIN_TAXPABLE_ACTIVITY not in", values, "mainTaxpableActivity");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityBetween(String value1, String value2) {
            addCriterion("MAIN_TAXPABLE_ACTIVITY between", value1, value2, "mainTaxpableActivity");
            return (Criteria) this;
        }

        public Criteria andMainTaxpableActivityNotBetween(String value1, String value2) {
            addCriterion("MAIN_TAXPABLE_ACTIVITY not between", value1, value2, "mainTaxpableActivity");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageIsNull() {
            addCriterion("PREFERRED_LANGUAGE is null");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageIsNotNull() {
            addCriterion("PREFERRED_LANGUAGE is not null");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageEqualTo(String value) {
            addCriterion("PREFERRED_LANGUAGE =", value, "preferredLanguage");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageNotEqualTo(String value) {
            addCriterion("PREFERRED_LANGUAGE <>", value, "preferredLanguage");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageGreaterThan(String value) {
            addCriterion("PREFERRED_LANGUAGE >", value, "preferredLanguage");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("PREFERRED_LANGUAGE >=", value, "preferredLanguage");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageLessThan(String value) {
            addCriterion("PREFERRED_LANGUAGE <", value, "preferredLanguage");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageLessThanOrEqualTo(String value) {
            addCriterion("PREFERRED_LANGUAGE <=", value, "preferredLanguage");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageLike(String value) {
            addCriterion("PREFERRED_LANGUAGE like", value, "preferredLanguage");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageNotLike(String value) {
            addCriterion("PREFERRED_LANGUAGE not like", value, "preferredLanguage");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageIn(List<String> values) {
            addCriterion("PREFERRED_LANGUAGE in", values, "preferredLanguage");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageNotIn(List<String> values) {
            addCriterion("PREFERRED_LANGUAGE not in", values, "preferredLanguage");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageBetween(String value1, String value2) {
            addCriterion("PREFERRED_LANGUAGE between", value1, value2, "preferredLanguage");
            return (Criteria) this;
        }

        public Criteria andPreferredLanguageNotBetween(String value1, String value2) {
            addCriterion("PREFERRED_LANGUAGE not between", value1, value2, "preferredLanguage");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeIsNull() {
            addCriterion("REGISTRATION_OFFICE is null");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeIsNotNull() {
            addCriterion("REGISTRATION_OFFICE is not null");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeEqualTo(String value) {
            addCriterion("REGISTRATION_OFFICE =", value, "registrationOffice");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeNotEqualTo(String value) {
            addCriterion("REGISTRATION_OFFICE <>", value, "registrationOffice");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeGreaterThan(String value) {
            addCriterion("REGISTRATION_OFFICE >", value, "registrationOffice");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeGreaterThanOrEqualTo(String value) {
            addCriterion("REGISTRATION_OFFICE >=", value, "registrationOffice");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeLessThan(String value) {
            addCriterion("REGISTRATION_OFFICE <", value, "registrationOffice");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeLessThanOrEqualTo(String value) {
            addCriterion("REGISTRATION_OFFICE <=", value, "registrationOffice");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeLike(String value) {
            addCriterion("REGISTRATION_OFFICE like", value, "registrationOffice");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeNotLike(String value) {
            addCriterion("REGISTRATION_OFFICE not like", value, "registrationOffice");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeIn(List<String> values) {
            addCriterion("REGISTRATION_OFFICE in", values, "registrationOffice");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeNotIn(List<String> values) {
            addCriterion("REGISTRATION_OFFICE not in", values, "registrationOffice");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeBetween(String value1, String value2) {
            addCriterion("REGISTRATION_OFFICE between", value1, value2, "registrationOffice");
            return (Criteria) this;
        }

        public Criteria andRegistrationOfficeNotBetween(String value1, String value2) {
            addCriterion("REGISTRATION_OFFICE not between", value1, value2, "registrationOffice");
            return (Criteria) this;
        }

        public Criteria andSysRegisteredTimeIsNull() {
            addCriterion("SYS_REGISTERED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSysRegisteredTimeIsNotNull() {
            addCriterion("SYS_REGISTERED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSysRegisteredTimeEqualTo(Date value) {
            addCriterion("SYS_REGISTERED_TIME =", value, "sysRegisteredTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisteredTimeNotEqualTo(Date value) {
            addCriterion("SYS_REGISTERED_TIME <>", value, "sysRegisteredTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisteredTimeGreaterThan(Date value) {
            addCriterion("SYS_REGISTERED_TIME >", value, "sysRegisteredTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisteredTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SYS_REGISTERED_TIME >=", value, "sysRegisteredTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisteredTimeLessThan(Date value) {
            addCriterion("SYS_REGISTERED_TIME <", value, "sysRegisteredTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisteredTimeLessThanOrEqualTo(Date value) {
            addCriterion("SYS_REGISTERED_TIME <=", value, "sysRegisteredTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisteredTimeIn(List<Date> values) {
            addCriterion("SYS_REGISTERED_TIME in", values, "sysRegisteredTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisteredTimeNotIn(List<Date> values) {
            addCriterion("SYS_REGISTERED_TIME not in", values, "sysRegisteredTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisteredTimeBetween(Date value1, Date value2) {
            addCriterion("SYS_REGISTERED_TIME between", value1, value2, "sysRegisteredTime");
            return (Criteria) this;
        }

        public Criteria andSysRegisteredTimeNotBetween(Date value1, Date value2) {
            addCriterion("SYS_REGISTERED_TIME not between", value1, value2, "sysRegisteredTime");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeIsNull() {
            addCriterion("TURNOVERSIZE is null");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeIsNotNull() {
            addCriterion("TURNOVERSIZE is not null");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeEqualTo(String value) {
            addCriterion("TURNOVERSIZE =", value, "turnoversize");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeNotEqualTo(String value) {
            addCriterion("TURNOVERSIZE <>", value, "turnoversize");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeGreaterThan(String value) {
            addCriterion("TURNOVERSIZE >", value, "turnoversize");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeGreaterThanOrEqualTo(String value) {
            addCriterion("TURNOVERSIZE >=", value, "turnoversize");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeLessThan(String value) {
            addCriterion("TURNOVERSIZE <", value, "turnoversize");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeLessThanOrEqualTo(String value) {
            addCriterion("TURNOVERSIZE <=", value, "turnoversize");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeLike(String value) {
            addCriterion("TURNOVERSIZE like", value, "turnoversize");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeNotLike(String value) {
            addCriterion("TURNOVERSIZE not like", value, "turnoversize");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeIn(List<String> values) {
            addCriterion("TURNOVERSIZE in", values, "turnoversize");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeNotIn(List<String> values) {
            addCriterion("TURNOVERSIZE not in", values, "turnoversize");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeBetween(String value1, String value2) {
            addCriterion("TURNOVERSIZE between", value1, value2, "turnoversize");
            return (Criteria) this;
        }

        public Criteria andTurnoversizeNotBetween(String value1, String value2) {
            addCriterion("TURNOVERSIZE not between", value1, value2, "turnoversize");
            return (Criteria) this;
        }

        public Criteria andEnterpriseScaleUidIsNull() {
            addCriterion("ENTERPRISE_SCALE_UID is null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseScaleUidIsNotNull() {
            addCriterion("ENTERPRISE_SCALE_UID is not null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseScaleUidEqualTo(BigDecimal value) {
            addCriterion("ENTERPRISE_SCALE_UID =", value, "enterpriseScaleUid");
            return (Criteria) this;
        }

        public Criteria andEnterpriseScaleUidNotEqualTo(BigDecimal value) {
            addCriterion("ENTERPRISE_SCALE_UID <>", value, "enterpriseScaleUid");
            return (Criteria) this;
        }

        public Criteria andEnterpriseScaleUidGreaterThan(BigDecimal value) {
            addCriterion("ENTERPRISE_SCALE_UID >", value, "enterpriseScaleUid");
            return (Criteria) this;
        }

        public Criteria andEnterpriseScaleUidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ENTERPRISE_SCALE_UID >=", value, "enterpriseScaleUid");
            return (Criteria) this;
        }

        public Criteria andEnterpriseScaleUidLessThan(BigDecimal value) {
            addCriterion("ENTERPRISE_SCALE_UID <", value, "enterpriseScaleUid");
            return (Criteria) this;
        }

        public Criteria andEnterpriseScaleUidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ENTERPRISE_SCALE_UID <=", value, "enterpriseScaleUid");
            return (Criteria) this;
        }

        public Criteria andEnterpriseScaleUidIn(List<BigDecimal> values) {
            addCriterion("ENTERPRISE_SCALE_UID in", values, "enterpriseScaleUid");
            return (Criteria) this;
        }

        public Criteria andEnterpriseScaleUidNotIn(List<BigDecimal> values) {
            addCriterion("ENTERPRISE_SCALE_UID not in", values, "enterpriseScaleUid");
            return (Criteria) this;
        }

        public Criteria andEnterpriseScaleUidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ENTERPRISE_SCALE_UID between", value1, value2, "enterpriseScaleUid");
            return (Criteria) this;
        }

        public Criteria andEnterpriseScaleUidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ENTERPRISE_SCALE_UID not between", value1, value2, "enterpriseScaleUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeUidIsNull() {
            addCriterion("TAXPAYER_TYPE_UID is null");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeUidIsNotNull() {
            addCriterion("TAXPAYER_TYPE_UID is not null");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeUidEqualTo(BigDecimal value) {
            addCriterion("TAXPAYER_TYPE_UID =", value, "taxpayerTypeUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeUidNotEqualTo(BigDecimal value) {
            addCriterion("TAXPAYER_TYPE_UID <>", value, "taxpayerTypeUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeUidGreaterThan(BigDecimal value) {
            addCriterion("TAXPAYER_TYPE_UID >", value, "taxpayerTypeUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeUidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TAXPAYER_TYPE_UID >=", value, "taxpayerTypeUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeUidLessThan(BigDecimal value) {
            addCriterion("TAXPAYER_TYPE_UID <", value, "taxpayerTypeUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeUidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TAXPAYER_TYPE_UID <=", value, "taxpayerTypeUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeUidIn(List<BigDecimal> values) {
            addCriterion("TAXPAYER_TYPE_UID in", values, "taxpayerTypeUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeUidNotIn(List<BigDecimal> values) {
            addCriterion("TAXPAYER_TYPE_UID not in", values, "taxpayerTypeUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeUidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TAXPAYER_TYPE_UID between", value1, value2, "taxpayerTypeUid");
            return (Criteria) this;
        }

        public Criteria andTaxpayerTypeUidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TAXPAYER_TYPE_UID not between", value1, value2, "taxpayerTypeUid");
            return (Criteria) this;
        }

        public Criteria andIndustryUidIsNull() {
            addCriterion("INDUSTRY_UID is null");
            return (Criteria) this;
        }

        public Criteria andIndustryUidIsNotNull() {
            addCriterion("INDUSTRY_UID is not null");
            return (Criteria) this;
        }

        public Criteria andIndustryUidEqualTo(BigDecimal value) {
            addCriterion("INDUSTRY_UID =", value, "industryUid");
            return (Criteria) this;
        }

        public Criteria andIndustryUidNotEqualTo(BigDecimal value) {
            addCriterion("INDUSTRY_UID <>", value, "industryUid");
            return (Criteria) this;
        }

        public Criteria andIndustryUidGreaterThan(BigDecimal value) {
            addCriterion("INDUSTRY_UID >", value, "industryUid");
            return (Criteria) this;
        }

        public Criteria andIndustryUidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INDUSTRY_UID >=", value, "industryUid");
            return (Criteria) this;
        }

        public Criteria andIndustryUidLessThan(BigDecimal value) {
            addCriterion("INDUSTRY_UID <", value, "industryUid");
            return (Criteria) this;
        }

        public Criteria andIndustryUidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INDUSTRY_UID <=", value, "industryUid");
            return (Criteria) this;
        }

        public Criteria andIndustryUidIn(List<BigDecimal> values) {
            addCriterion("INDUSTRY_UID in", values, "industryUid");
            return (Criteria) this;
        }

        public Criteria andIndustryUidNotIn(List<BigDecimal> values) {
            addCriterion("INDUSTRY_UID not in", values, "industryUid");
            return (Criteria) this;
        }

        public Criteria andIndustryUidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INDUSTRY_UID between", value1, value2, "industryUid");
            return (Criteria) this;
        }

        public Criteria andIndustryUidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INDUSTRY_UID not between", value1, value2, "industryUid");
            return (Criteria) this;
        }

        public Criteria andIsCompletedIsNull() {
            addCriterion("IS_COMPLETED is null");
            return (Criteria) this;
        }

        public Criteria andIsCompletedIsNotNull() {
            addCriterion("IS_COMPLETED is not null");
            return (Criteria) this;
        }

        public Criteria andIsCompletedEqualTo(String value) {
            addCriterion("IS_COMPLETED =", value, "isCompleted");
            return (Criteria) this;
        }

        public Criteria andIsCompletedNotEqualTo(String value) {
            addCriterion("IS_COMPLETED <>", value, "isCompleted");
            return (Criteria) this;
        }

        public Criteria andIsCompletedGreaterThan(String value) {
            addCriterion("IS_COMPLETED >", value, "isCompleted");
            return (Criteria) this;
        }

        public Criteria andIsCompletedGreaterThanOrEqualTo(String value) {
            addCriterion("IS_COMPLETED >=", value, "isCompleted");
            return (Criteria) this;
        }

        public Criteria andIsCompletedLessThan(String value) {
            addCriterion("IS_COMPLETED <", value, "isCompleted");
            return (Criteria) this;
        }

        public Criteria andIsCompletedLessThanOrEqualTo(String value) {
            addCriterion("IS_COMPLETED <=", value, "isCompleted");
            return (Criteria) this;
        }

        public Criteria andIsCompletedLike(String value) {
            addCriterion("IS_COMPLETED like", value, "isCompleted");
            return (Criteria) this;
        }

        public Criteria andIsCompletedNotLike(String value) {
            addCriterion("IS_COMPLETED not like", value, "isCompleted");
            return (Criteria) this;
        }

        public Criteria andIsCompletedIn(List<String> values) {
            addCriterion("IS_COMPLETED in", values, "isCompleted");
            return (Criteria) this;
        }

        public Criteria andIsCompletedNotIn(List<String> values) {
            addCriterion("IS_COMPLETED not in", values, "isCompleted");
            return (Criteria) this;
        }

        public Criteria andIsCompletedBetween(String value1, String value2) {
            addCriterion("IS_COMPLETED between", value1, value2, "isCompleted");
            return (Criteria) this;
        }

        public Criteria andIsCompletedNotBetween(String value1, String value2) {
            addCriterion("IS_COMPLETED not between", value1, value2, "isCompleted");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyIsNull() {
            addCriterion("ALLOW_FOREIGN_CURRENCY is null");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyIsNotNull() {
            addCriterion("ALLOW_FOREIGN_CURRENCY is not null");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyEqualTo(String value) {
            addCriterion("ALLOW_FOREIGN_CURRENCY =", value, "allowForeignCurrency");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyNotEqualTo(String value) {
            addCriterion("ALLOW_FOREIGN_CURRENCY <>", value, "allowForeignCurrency");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyGreaterThan(String value) {
            addCriterion("ALLOW_FOREIGN_CURRENCY >", value, "allowForeignCurrency");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("ALLOW_FOREIGN_CURRENCY >=", value, "allowForeignCurrency");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyLessThan(String value) {
            addCriterion("ALLOW_FOREIGN_CURRENCY <", value, "allowForeignCurrency");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyLessThanOrEqualTo(String value) {
            addCriterion("ALLOW_FOREIGN_CURRENCY <=", value, "allowForeignCurrency");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyLike(String value) {
            addCriterion("ALLOW_FOREIGN_CURRENCY like", value, "allowForeignCurrency");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyNotLike(String value) {
            addCriterion("ALLOW_FOREIGN_CURRENCY not like", value, "allowForeignCurrency");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyIn(List<String> values) {
            addCriterion("ALLOW_FOREIGN_CURRENCY in", values, "allowForeignCurrency");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyNotIn(List<String> values) {
            addCriterion("ALLOW_FOREIGN_CURRENCY not in", values, "allowForeignCurrency");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyBetween(String value1, String value2) {
            addCriterion("ALLOW_FOREIGN_CURRENCY between", value1, value2, "allowForeignCurrency");
            return (Criteria) this;
        }

        public Criteria andAllowForeignCurrencyNotBetween(String value1, String value2) {
            addCriterion("ALLOW_FOREIGN_CURRENCY not between", value1, value2, "allowForeignCurrency");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("IS_DELETED is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("IS_DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("IS_DELETED =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("IS_DELETED <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("IS_DELETED >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DELETED >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("IS_DELETED <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("IS_DELETED <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("IS_DELETED like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("IS_DELETED not like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("IS_DELETED in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("IS_DELETED not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("IS_DELETED between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("IS_DELETED not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdIsNull() {
            addCriterion("REG_ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdIsNotNull() {
            addCriterion("REG_ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdEqualTo(String value) {
            addCriterion("REG_ORG_ID =", value, "regOrgId");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdNotEqualTo(String value) {
            addCriterion("REG_ORG_ID <>", value, "regOrgId");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdGreaterThan(String value) {
            addCriterion("REG_ORG_ID >", value, "regOrgId");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("REG_ORG_ID >=", value, "regOrgId");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdLessThan(String value) {
            addCriterion("REG_ORG_ID <", value, "regOrgId");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdLessThanOrEqualTo(String value) {
            addCriterion("REG_ORG_ID <=", value, "regOrgId");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdLike(String value) {
            addCriterion("REG_ORG_ID like", value, "regOrgId");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdNotLike(String value) {
            addCriterion("REG_ORG_ID not like", value, "regOrgId");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdIn(List<String> values) {
            addCriterion("REG_ORG_ID in", values, "regOrgId");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdNotIn(List<String> values) {
            addCriterion("REG_ORG_ID not in", values, "regOrgId");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdBetween(String value1, String value2) {
            addCriterion("REG_ORG_ID between", value1, value2, "regOrgId");
            return (Criteria) this;
        }

        public Criteria andRegOrgIdNotBetween(String value1, String value2) {
            addCriterion("REG_ORG_ID not between", value1, value2, "regOrgId");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeIsNull() {
            addCriterion("CRT_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeIsNotNull() {
            addCriterion("CRT_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeEqualTo(Date value) {
            addCriterion("CRT_DATETIME =", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeNotEqualTo(Date value) {
            addCriterion("CRT_DATETIME <>", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeGreaterThan(Date value) {
            addCriterion("CRT_DATETIME >", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CRT_DATETIME >=", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeLessThan(Date value) {
            addCriterion("CRT_DATETIME <", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CRT_DATETIME <=", value, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeIn(List<Date> values) {
            addCriterion("CRT_DATETIME in", values, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeNotIn(List<Date> values) {
            addCriterion("CRT_DATETIME not in", values, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeBetween(Date value1, Date value2) {
            addCriterion("CRT_DATETIME between", value1, value2, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andCrtDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CRT_DATETIME not between", value1, value2, "crtDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNull() {
            addCriterion("INSERT_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNotNull() {
            addCriterion("INSERT_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdEqualTo(String value) {
            addCriterion("INSERT_USER_ID =", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotEqualTo(String value) {
            addCriterion("INSERT_USER_ID <>", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThan(String value) {
            addCriterion("INSERT_USER_ID >", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("INSERT_USER_ID >=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThan(String value) {
            addCriterion("INSERT_USER_ID <", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThanOrEqualTo(String value) {
            addCriterion("INSERT_USER_ID <=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLike(String value) {
            addCriterion("INSERT_USER_ID like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotLike(String value) {
            addCriterion("INSERT_USER_ID not like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIn(List<String> values) {
            addCriterion("INSERT_USER_ID in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotIn(List<String> values) {
            addCriterion("INSERT_USER_ID not in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdBetween(String value1, String value2) {
            addCriterion("INSERT_USER_ID between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotBetween(String value1, String value2) {
            addCriterion("INSERT_USER_ID not between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andLastModDatetimeIsNull() {
            addCriterion("LAST_MOD_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andLastModDatetimeIsNotNull() {
            addCriterion("LAST_MOD_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastModDatetimeEqualTo(Date value) {
            addCriterion("LAST_MOD_DATETIME =", value, "lastModDatetime");
            return (Criteria) this;
        }

        public Criteria andLastModDatetimeNotEqualTo(Date value) {
            addCriterion("LAST_MOD_DATETIME <>", value, "lastModDatetime");
            return (Criteria) this;
        }

        public Criteria andLastModDatetimeGreaterThan(Date value) {
            addCriterion("LAST_MOD_DATETIME >", value, "lastModDatetime");
            return (Criteria) this;
        }

        public Criteria andLastModDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_MOD_DATETIME >=", value, "lastModDatetime");
            return (Criteria) this;
        }

        public Criteria andLastModDatetimeLessThan(Date value) {
            addCriterion("LAST_MOD_DATETIME <", value, "lastModDatetime");
            return (Criteria) this;
        }

        public Criteria andLastModDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_MOD_DATETIME <=", value, "lastModDatetime");
            return (Criteria) this;
        }

        public Criteria andLastModDatetimeIn(List<Date> values) {
            addCriterion("LAST_MOD_DATETIME in", values, "lastModDatetime");
            return (Criteria) this;
        }

        public Criteria andLastModDatetimeNotIn(List<Date> values) {
            addCriterion("LAST_MOD_DATETIME not in", values, "lastModDatetime");
            return (Criteria) this;
        }

        public Criteria andLastModDatetimeBetween(Date value1, Date value2) {
            addCriterion("LAST_MOD_DATETIME between", value1, value2, "lastModDatetime");
            return (Criteria) this;
        }

        public Criteria andLastModDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_MOD_DATETIME not between", value1, value2, "lastModDatetime");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdIsNull() {
            addCriterion("LAST_MOD_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdIsNotNull() {
            addCriterion("LAST_MOD_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdEqualTo(String value) {
            addCriterion("LAST_MOD_USER_ID =", value, "lastModUserId");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdNotEqualTo(String value) {
            addCriterion("LAST_MOD_USER_ID <>", value, "lastModUserId");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdGreaterThan(String value) {
            addCriterion("LAST_MOD_USER_ID >", value, "lastModUserId");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_MOD_USER_ID >=", value, "lastModUserId");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdLessThan(String value) {
            addCriterion("LAST_MOD_USER_ID <", value, "lastModUserId");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdLessThanOrEqualTo(String value) {
            addCriterion("LAST_MOD_USER_ID <=", value, "lastModUserId");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdLike(String value) {
            addCriterion("LAST_MOD_USER_ID like", value, "lastModUserId");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdNotLike(String value) {
            addCriterion("LAST_MOD_USER_ID not like", value, "lastModUserId");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdIn(List<String> values) {
            addCriterion("LAST_MOD_USER_ID in", values, "lastModUserId");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdNotIn(List<String> values) {
            addCriterion("LAST_MOD_USER_ID not in", values, "lastModUserId");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdBetween(String value1, String value2) {
            addCriterion("LAST_MOD_USER_ID between", value1, value2, "lastModUserId");
            return (Criteria) this;
        }

        public Criteria andLastModUserIdNotBetween(String value1, String value2) {
            addCriterion("LAST_MOD_USER_ID not between", value1, value2, "lastModUserId");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecIsNull() {
            addCriterion("TIN_OFFICE_IN_SEC is null");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecIsNotNull() {
            addCriterion("TIN_OFFICE_IN_SEC is not null");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecEqualTo(String value) {
            addCriterion("TIN_OFFICE_IN_SEC =", value, "tinOfficeInSec");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecNotEqualTo(String value) {
            addCriterion("TIN_OFFICE_IN_SEC <>", value, "tinOfficeInSec");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecGreaterThan(String value) {
            addCriterion("TIN_OFFICE_IN_SEC >", value, "tinOfficeInSec");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecGreaterThanOrEqualTo(String value) {
            addCriterion("TIN_OFFICE_IN_SEC >=", value, "tinOfficeInSec");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecLessThan(String value) {
            addCriterion("TIN_OFFICE_IN_SEC <", value, "tinOfficeInSec");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecLessThanOrEqualTo(String value) {
            addCriterion("TIN_OFFICE_IN_SEC <=", value, "tinOfficeInSec");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecLike(String value) {
            addCriterion("TIN_OFFICE_IN_SEC like", value, "tinOfficeInSec");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecNotLike(String value) {
            addCriterion("TIN_OFFICE_IN_SEC not like", value, "tinOfficeInSec");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecIn(List<String> values) {
            addCriterion("TIN_OFFICE_IN_SEC in", values, "tinOfficeInSec");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecNotIn(List<String> values) {
            addCriterion("TIN_OFFICE_IN_SEC not in", values, "tinOfficeInSec");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecBetween(String value1, String value2) {
            addCriterion("TIN_OFFICE_IN_SEC between", value1, value2, "tinOfficeInSec");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInSecNotBetween(String value1, String value2) {
            addCriterion("TIN_OFFICE_IN_SEC not between", value1, value2, "tinOfficeInSec");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngIsNull() {
            addCriterion("TIN_OFFICE_IN_ENG is null");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngIsNotNull() {
            addCriterion("TIN_OFFICE_IN_ENG is not null");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngEqualTo(String value) {
            addCriterion("TIN_OFFICE_IN_ENG =", value, "tinOfficeInEng");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngNotEqualTo(String value) {
            addCriterion("TIN_OFFICE_IN_ENG <>", value, "tinOfficeInEng");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngGreaterThan(String value) {
            addCriterion("TIN_OFFICE_IN_ENG >", value, "tinOfficeInEng");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngGreaterThanOrEqualTo(String value) {
            addCriterion("TIN_OFFICE_IN_ENG >=", value, "tinOfficeInEng");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngLessThan(String value) {
            addCriterion("TIN_OFFICE_IN_ENG <", value, "tinOfficeInEng");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngLessThanOrEqualTo(String value) {
            addCriterion("TIN_OFFICE_IN_ENG <=", value, "tinOfficeInEng");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngLike(String value) {
            addCriterion("TIN_OFFICE_IN_ENG like", value, "tinOfficeInEng");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngNotLike(String value) {
            addCriterion("TIN_OFFICE_IN_ENG not like", value, "tinOfficeInEng");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngIn(List<String> values) {
            addCriterion("TIN_OFFICE_IN_ENG in", values, "tinOfficeInEng");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngNotIn(List<String> values) {
            addCriterion("TIN_OFFICE_IN_ENG not in", values, "tinOfficeInEng");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngBetween(String value1, String value2) {
            addCriterion("TIN_OFFICE_IN_ENG between", value1, value2, "tinOfficeInEng");
            return (Criteria) this;
        }

        public Criteria andTinOfficeInEngNotBetween(String value1, String value2) {
            addCriterion("TIN_OFFICE_IN_ENG not between", value1, value2, "tinOfficeInEng");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 20 11:24:37 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_TAXPAYER
     *
     * @mbggenerated Fri Apr 20 11:24:37 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}